### PR TITLE
Packaging + testing

### PR DESCRIPTION
**Pull request by sydneyli**
A bit of a re-org to existing structure, but includes packaging (`requirements.txt => setup.py`) and testing infra (`tox` running `pylint` and `pytest`).

### CODE REVIEW

**Comment by sydneyli** [comment]
Seems like git didn't recognize some of the file renaming that happened here, so essentially:
`starttls-policy/*_test.py => starttls-policy/starttls_policy/tests/*.py`
`starttls-policy/*.py => starttls-policy/starttls_policy/*.py`
Packaging + testing configuration files live in `starttls-policy` root
Moved old code to `code_legacy`
Removed `vagrant` integration testing (All of this code has been migrated into the Docker integration testing code for Certbot's Postfix plugin)

@jgillula Let me know if you have any questions about the PR-- it looks a lot bigger than it actually is!

**Comment by jgillula** [comment]
I'm getting an error when I run `tox -e py27` in `starttls-policy`:

```GLOB sdist-make: /home/jeremy/Temp/starttls-everywhere/starttls-policy/setup.py
py27 inst-nodeps: /home/jeremy/Temp/starttls-everywhere/starttls-policy/.tox/dist/starttls_policy-0.0.1.dev0.zip
py27 installed: DateTime==4.2,argparse==1.2.1,astroid==1.6.2,attrs==17.4.0,backports.functools-lru-cache==1.5,configparser==3.5.0,enum34==1.1.6,funcsigs==1.0.2,futures==3.2.0,isort==4.3.4,lazy-object-proxy==1.3.1,mccabe==0.6.1,mock==2.0.0,more-itertools==4.1.0,pbr==4.0.0,pluggy==0.6.0,py==1.5.3,pycurl==7.43.0.1,pylint==1.8.3,pytest==3.5.0,python-dateutil==2.7.2,pytz==2018.3,singledispatch==3.4.0.3,six==1.11.0,starttls-policy==0.0.1.dev0,wrapt==1.10.11,wsgiref==0.1.2,zope.interface==4.4.3
py27 runtests: PYTHONHASHSEED='520349807'
py27 runtests: commands[0] | pip install -e .
Obtaining file:///home/jeremy/Temp/starttls-everywhere/starttls-policy
  Running setup.py (path:/home/jeremy/Temp/starttls-everywhere/starttls-policy/setup.py) egg_info for package from file:///home/jeremy/Temp/starttls-everywhere/starttls-policy
    
Requirement already satisfied (use --upgrade to upgrade): datetime in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pycurl in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pytest in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): mock in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Requirement already satisfied (use --upgrade to upgrade): pylint in ./.tox/py27/lib/python2.7/site-packages (from starttls-policy==0.0.1.dev0)
Installing collected packages: starttls-policy
  Running setup.py develop for starttls-policy
    
    Creating /home/jeremy/Temp/starttls-everywhere/starttls-policy/.tox/py27/lib/python2.7/site-packages/starttls-policy.egg-link (link to .)
    Adding starttls-policy 0.0.1.dev0 to easy-install.pth file
    
    Installed /home/jeremy/Temp/starttls-everywhere/starttls-policy
Successfully installed starttls-policy
Cleaning up...
py27 runtests: commands[1] | pytest starttls_policy
================================================== test session starts ===================================================
platform linux2 -- Python 2.7.6, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/jeremy/Temp/starttls-everywhere/starttls-policy, inifile:
collected 3 items                                                                                                        

starttls_policy/tests/policy_test.py .                                                                             [ 33%]
starttls_policy/tests/update_test.py FF                                                                            [100%]

======================================================== FAILURES ========================================================
______________________________________ TestUpdate.test_no_update_when_not_outdated _______________________________________
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1297: in patched
    arg = patching.__enter__()
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1353: in __enter__
    self.target = self.getter()
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1523: in <lambda>
    getter = lambda: _importer(target)
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1210: in _importer
    thing = _dot_lookup(thing, comp, import_path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

thing = <module 'starttls_policy.update' from '/home/jeremy/Temp/starttls-everywhere/starttls-policy/starttls_policy/update.pyc'>
comp = 'policy', import_path = 'starttls_policy.update.policy'

    def _dot_lookup(thing, comp, import_path):
        try:
            return getattr(thing, comp)
        except AttributeError:
>           __import__(import_path)
E           ImportError: No module named policy

.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1199: ImportError
__________________________________________ TestUpdate.test_update_when_outdated __________________________________________
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1297: in patched
    arg = patching.__enter__()
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1353: in __enter__
    self.target = self.getter()
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1523: in <lambda>
    getter = lambda: _importer(target)
.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1210: in _importer
    thing = _dot_lookup(thing, comp, import_path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

thing = <module 'starttls_policy.update' from '/home/jeremy/Temp/starttls-everywhere/starttls-policy/starttls_policy/update.pyc'>
comp = 'policy', import_path = 'starttls_policy.update.policy'

    def _dot_lookup(thing, comp, import_path):
        try:
            return getattr(thing, comp)
        except AttributeError:
>           __import__(import_path)
E           ImportError: No module named policy

.tox/py27/local/lib/python2.7/site-packages/mock/mock.py:1199: ImportError
=========================================== 2 failed, 1 passed in 0.45 seconds ===========================================
ERROR: InvocationError: '/home/jeremy/Temp/starttls-everywhere/starttls-policy/.tox/py27/bin/pytest starttls_policy'
________________________________________________________ summary _________________________________________________________
ERROR:   py27: commands failed
```
This could just be me being stupid and missing something?

**Comment by sydneyli** [comment]
Nope, that's my bad! Just pushed a fix. I just noted that the PR is also missing one set of unittests that I'll push once I get back to my laptop tonight.

**Comment by sydneyli** [comment]
(rebased to resolve merge conflict)

**Pull request merged**
