### PR TITLE
add JSON schema for policy.json

### PR DESCRIPTION
**Pull request by Snawoot**
Adds [JSON schema](http://json-schema.org) for policy list in order to define it and validate it.

### CODE REVIEW

**Comment by Snawoot** [comment]
Added more restrictions for lists

**Comment by Snawoot** [comment]
If you like to implement automatic checks, let me suggest you a [schema validator](https://github.com/Julian/jsonschema) written in Python. Despite listing on json-schema.org, it actually supports latest version of jsonschema.

**Comment by Snawoot** [comment]
Added schema versioning. Now we require strict match of schema and instance version.

**Comment by Snawoot** [comment]
Disallowed pinsets with empty hash list

**Comment by Snawoot** [comment]
Added autotests

**Comment by Snawoot** [comment]
Rebased

**Comment by Snawoot** [comment]
Rebased on top of policy list without retired fields. Added last commit which adjusts spec and tests to fields retirement.

**Comment by Snawoot** [comment]
@jgillula @sydneyli I think now it's ready to be reviewed and merged.

**Comment by Snawoot** [comment]
@jgillula @sydneyli Any response?

**Comment by maximillianh** [comment]
Apologies for the delay, @Snawoot  -- we should be able to review this this week.

**Pull request merged**
