### PR TITLE
Add datahoarder.dev and kokomo.xyz

### PR DESCRIPTION
**Pull request by whalehub**
I'm the admin of both domains and configured them according to the requirements on the [STARTTLS Everywhere](https://starttls-everywhere.org/) website.

I submitted both domains on the site a few months ago but they still haven't appeared in the `policy.json` list despite continuously fulfilling the requirements, hence this pull request.

### CODE REVIEW

**Comment by whalehub** [comment]
@m0namon How come nobody has been taking a look at this and all the other pull requests on this repo since 2018?

**Comment by whalehub** [comment]
@m0namon @azet @sydneyli How come nobody has been taking a look at this and all the other pull requests on this repo since 2018? Is MTA-STS even maintained as a project anymore?

**Comment by m0namon** [comment]
Hi @whalehub -- thanks for your interest in the project! The most recent update has been delayed on our end. We don't have many resources to maintain this project at the moment and are still trying to constantly improve it.

As for the pull requests, we've been prioritizing submissions through the site as it automatically kicks off our automation pipeline. Your most recent additions will be added in the next update.

**Comment by whalehub** [comment]
@m0namon Thanks for the response. I'd suggest just disabling pull requests for this repo if there is no one on the team that checks them regularly.

**Comment by whalehub** [comment]
@m0namon It's been almost two months since you said that my additions will be added in the next update yet the STARTTLS Everywhere website reports that my domains are still "queued to be added to the STARTTLS policy list." What's up with that?

**Pull request closed without merging**
