### PR TITLE
set _all_ client&server options to exclude v2 and v3 #24

### PR DESCRIPTION
**Pull request by azet**

### CODE REVIEW

**Comment by pde** [comment]
Discussion: it's a little unclear why there are two types of TLS settings in postfix, when there seem to be three applicable cases:

* Inbound email from a mail client
* Inbound email relayed from another MTA
* Outbound email relayed to another MTA

In any case, we do probably want to force TLS 1.0+ for all of these, so LGTM.

**Comment by pde** [comment]
Oh, except: the "mandatory" TLS field may apply to Postfix instances where TLS is strictly required. It's *probably* fine to set that, but may be safer and cleaner to only set it if the admin has enabled mandatory TLS.

**Comment by azet** [comment]
The Postfix documentations for both `smtpd_mandatory_protocols` and `smtp_mandatory_protocols`:
```
The default value is "!SSLv2, !SSLv3" for Postfix releases after the middle of 2015, "!SSLv2" for older releases.
```
Assuming this is true, we should set this option for previous releases as well.

**NOTE**: all of these settings depend on which option is set in `smtp_tls_policy_maps`: http://www.postfix.org/postconf.5.html#smtp_tls_policy_maps
..and may override each other. we currently set `may`.

**Comment by pde** [comment]
Looks reasonable, though we should probably make all of these enhancements user-disableable before we ship this for real. I'll open another ticket for that.

**Comment by azet** [comment]
@pde Should we merge this?

**Comment by pde** [comment]
LGTM.

**Pull request merged**
